service: serverless-qa

provider:
  name: aws # provider
  region: eu-west-1 # aws region
  memorySize: 2000 # optional, in MB, default is 1024
  timeout: 60 # optional, in seconds, default is 6

functions:
  questionanswering:
    image: 099624017219.dkr.ecr.eu-west-1.amazonaws.com/qa-lambda:latest #ecr url
    events:
      - http:
          path: qa # http path
          method: post # http method
          cors: true